"""
11 — JEV post-2022 sub-period composition check: does the administrative-error
dominance of post-2022 JEV reporting persist into 2024-2025, or is the 2025 peak
a second wave of reactogenicity?

Splits the post-2022 period (2022-2023 vs 2024-2025, plus 2025 alone) and reports,
per sub-period, the share of PT occurrences that are administrative/programmatic
errors vs classical reactions. Reuses the same JEV case matching as 07_temporal.py.

Inputs (data/processed/): daen_cases.parquet, daen_case_drugs.parquet,
  daen_case_reactions.parquet (generated by scripts 01-02)
Output (outputs/tables/): temporal_jev_subperiod_composition.csv (Supplementary Table S7)

Usage:
    python scripts/11_temporal_subperiod.py
"""
from pathlib import Path
import re
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "data" / "processed"
OUT = ROOT / "outputs" / "tables" / "temporal_jev_subperiod_composition.csv"

# Administrative / programmatic error PTs (delivery-process events, not reactions).
ERROR_RE = re.compile(
    r"incorrect route|vaccination error|contraindication to vaccination|"
    r"contraindicated product|inappropriate schedule|inappropriate age|"
    r"product administered to patient of inappropriate age|overdose|underdose|"
    r"prescribing issue|expired product|incorrect dose|wrong product|"
    r"wrong technique|administered at inappropriate site|dispensing error|"
    r"medication error|product use issue|off-label|poor quality product|"
    r"product administration error|product preparation",
    re.I,
)
# Classical reaction / reactogenicity PTs (clinical AEs).
REACTION_RE = re.compile(
    r"headache|urticaria|injection site|pyrexia|vomiting|nausea|rash|pruritus|"
    r"myalgia|arthralgia|dizziness|fatigue|malaise|erythema|oedema|angioedema|"
    r"hypersensitivity|anaphyla|fever|chills|paraesthesia|lymphadenopathy|"
    r"dyspnoea|photophobia|swelling|pain in extremity|influenza like illness|"
    r"bronchospasm|hypotension|throat tightness|face oedema|periorbital",
    re.I,
)


def classify(pt: str) -> str:
    if ERROR_RE.search(pt):
        return "error"
    if REACTION_RE.search(pt):
        return "reaction"
    return "other"


def main():
    cases = pd.read_parquet(PROCESSED / "daen_cases.parquet")
    case_drugs = pd.read_parquet(PROCESSED / "daen_case_drugs.parquet")
    case_reactions = pd.read_parquet(PROCESSED / "daen_case_reactions.parquet")

    jev_cases = case_drugs.loc[case_drugs["canonical_name"] == "JEV vaccines",
                               "case_number"].drop_duplicates()
    cr = case_reactions[case_reactions["case_number"].isin(jev_cases)].merge(
        cases[["case_number", "report_date"]], on="case_number").copy()
    cr["year"] = cr["report_date"].dt.year
    cr["klass"] = cr["reaction_pt"].map(classify)

    def period(y):
        if y < 2022:
            return "pre_2022"
        if y <= 2023:
            return "2022-2023"
        return "2024-2026"

    cr["subperiod"] = cr["year"].map(period)

    rows = []
    groups = [("pre_2022", cr["subperiod"] == "pre_2022"),
              ("2022-2023", cr["subperiod"] == "2022-2023"),
              ("2024-2026", cr["subperiod"] == "2024-2026"),
              ("2025-only", cr["year"] == 2025)]
    print(f"{'subperiod':<12}{'reports':>8}{'PTocc':>7}{'err':>6}{'rxn':>6}{'oth':>6}"
          f"{'err%':>7}{'rxn%':>7}")
    for name, mask in groups:
        g = cr[mask]
        n_reports = g["case_number"].nunique()
        n_pt = len(g)
        vc = g["klass"].value_counts()
        err, rxn, oth = int(vc.get("error", 0)), int(vc.get("reaction", 0)), int(vc.get("other", 0))
        errpct = 100 * err / n_pt if n_pt else 0
        rxnpct = 100 * rxn / n_pt if n_pt else 0
        print(f"{name:<12}{n_reports:>8}{n_pt:>7}{err:>6}{rxn:>6}{oth:>6}{errpct:>6.0f}%{rxnpct:>6.0f}%")
        # reports with >=1 error PT
        rep_err = g.loc[g["klass"] == "error", "case_number"].nunique()
        rows.append({"subperiod": name, "n_reports": n_reports, "pt_occurrences": n_pt,
                     "error_pt": err, "reaction_pt": rxn, "other_pt": oth,
                     "error_pct": round(errpct, 1), "reaction_pct": round(rxnpct, 1),
                     "reports_with_error": rep_err,
                     "pct_reports_with_error": round(100 * rep_err / n_reports, 1) if n_reports else 0})

    print("\nTop error PTs by sub-period:")
    for name, mask in groups[1:]:
        g = cr[(mask) & (cr["klass"] == "error")]
        top = g["reaction_pt"].value_counts().head(5)
        print(f"  {name}: " + "; ".join(f"{pt} ({n})" for pt, n in top.items()))
    print("\nTop reaction PTs by sub-period:")
    for name, mask in groups[1:]:
        g = cr[(mask) & (cr["klass"] == "reaction")]
        top = g["reaction_pt"].value_counts().head(5)
        print(f"  {name}: " + "; ".join(f"{pt} ({n})" for pt, n in top.items()))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(OUT, index=False)
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()
