"""
12 — Generate Figure 1 for the JEV standalone paper: quarterly JEV-vaccine report
counts with ALL PELT-detected change points shown (the two substantive anchors
highlighted, the five minor pre-outbreak ones shown as faint markers).

Every change point detected by PELT is drawn, not only the pre-specified
outbreak anchor.

Inputs (outputs/tables/): temporal_jev_quarterly.csv, temporal_jev_changepoint.csv
  (generated by 07_temporal.py)
Outputs (outputs/figures/): figure_jev_temporal.pdf / .png
"""

import os
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

try:  # optional text guard for rendered labels; used only if on PYTHONPATH
    import _integrity_guard  # noqa: F401
except ImportError:
    pass

OUTPUTS = Path(__file__).resolve().parent.parent / "outputs"
TABLES = OUTPUTS / "tables"
FIGURES = OUTPUTS / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

BLUE = "#0072B2"
VERMIL = "#D55E00"
GREY = "#999999"

plt.rcParams.update({
    "font.family": "sans-serif", "font.size": 9, "axes.titlesize": 10,
    "axes.labelsize": 9, "xtick.labelsize": 8, "ytick.labelsize": 8,
    "legend.fontsize": 8, "figure.dpi": 300, "savefig.dpi": 300,
    "savefig.bbox": "tight", "savefig.pad_inches": 0.15,
})

# Substantive anchors to annotate (the rest are shown but not labelled).
# (label, colour, ha, x-offset pts, y-fraction) — staggered to avoid collision.
ANCHORS = {
    "2021Q4": ("2021Q4\noutbreak onset", VERMIL, "right", -6, 0.96),
    "2024Q2": ("2024Q2\n2025 resurgence", BLUE, "left", 6, 0.78),
}


def quarter_to_date(q: str) -> pd.Timestamp:
    year, qn = int(q[:4]), int(q[-1])
    return pd.Timestamp(year=year, month={1: 1, 2: 4, 3: 7, 4: 10}[qn], day=1)


def build():
    df = pd.read_csv(TABLES / "temporal_jev_quarterly.csv")
    cp = pd.read_csv(TABLES / "temporal_jev_changepoint.csv")
    df = df.assign(date=df["quarter"].apply(quarter_to_date))
    cp = cp.assign(date=cp["cp_quarter"].apply(quarter_to_date))

    fig, ax = plt.subplots(figsize=(8.5, 3.6))
    ax.bar(df["date"], df["n_reports"], width=80, color="#4C72B0", alpha=0.85,
           edgecolor="none", zorder=2)

    for _, row in cp.iterrows():
        q = row["cp_quarter"]
        if q in ANCHORS:
            label, colour, ha, dx, yfrac = ANCHORS[q]
            ax.axvline(row["date"], color=colour, linewidth=1.5, zorder=3)
            ax.annotate(label, xy=(row["date"], ax.get_ylim()[1] * yfrac),
                        xytext=(dx, -2), textcoords="offset points",
                        fontsize=7.5, color=colour, va="top", ha=ha)
        else:
            ax.axvline(row["date"], color=GREY, linewidth=0.8, linestyle="--",
                       alpha=0.5, zorder=1)

    ax.set_ylabel("Reports per quarter")
    ax.set_xlabel("Quarter")
    ax.set_title("Quarterly Japanese encephalitis vaccine adverse event reports, "
                 "Australia (DAEN), 1988-2026")
    ax.text(0.01, 0.95,
            "Dashed grey lines: 5 minor pre-outbreak PELT change points "
            "(1999Q2, 2000Q3, 2004Q2, 2013Q1, 2014Q2)",
            transform=ax.transAxes, fontsize=6.5, color=GREY, va="top")

    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)

    fig.tight_layout()
    cwd = os.getcwd()
    os.chdir(FIGURES)
    try:
        for ext in ("pdf", "png"):
            fig.savefig(f"figure_jev_temporal.{ext}")
    finally:
        os.chdir(cwd)
    plt.close(fig)
    print(f"Wrote {FIGURES / 'figure_jev_temporal.pdf'} (+ .png)")


# Usage: python scripts/12_figure_jev_temporal.py

if __name__ == "__main__":
    build()
