"""
13 — Generate Figure 2 for the JEV standalone paper: the pre/post-2022 shift in
report composition, expressed as PER-QUARTER reporting RATES (not raw period
counts).

Per-quarter rates avoid the unequal-period-length artefact: there are 136
pre-2022 quarters and 18 post-2022 quarters, so raw counts overstate any
apparent decline in classical reactions. On a per-quarter basis, classical
reactions hold roughly steady while administrative errors emerge on top.

Style: plain matplotlib (matching figure_jev_temporal) with the
Okabe-Ito colourblind-safe palette (blue = classical reactions, vermillion =
administrative errors, orange = population-shift indicator).

Inputs (outputs/tables/): temporal_jev_pt_shift.csv, temporal_jev_quarterly.csv
  (generated by 07_temporal.py)
Outputs (outputs/figures/): figure_jev_pt_shift.pdf / .png
"""

import os
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

try:  # optional text guard for rendered labels; used only if on PYTHONPATH
    import _integrity_guard  # noqa: F401
except ImportError:
    pass

OUTPUTS = Path(__file__).resolve().parent.parent / "outputs"
TABLES = OUTPUTS / "tables"
FIGURES = OUTPUTS / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

# Okabe-Ito identities (shared palette).
BLUE = "#0072B2"     # classical reactions
VERMIL = "#D55E00"   # administrative errors
ORANGE = "#E69F00"   # population-shift indicator
GREY = "#999999"

# Period lengths (quarters) from the quarterly series: 1988Q1-2021Q4 and
# 2022Q1-2026Q2. Checked against temporal_jev_quarterly.csv at run time.
N_PRE_Q = 136
N_POST_Q = 18

plt.rcParams.update({
    "font.family": "sans-serif",
    "font.size": 9,
    "axes.titlesize": 10,
    "axes.labelsize": 9,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "legend.fontsize": 8,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.15,
})

# (label, csv_key, pre_n, post_n, category)
CLASSICAL = [
    ("Headache", "Headache", 48, 7),
    ("Urticaria", "Urticaria", 32, 3),
    ("Injection-site pain", "Injection site pain", 12, 1),
]
ERRORS = [
    ("Incorrect route of administration", "Incorrect route of product administration", 1, 25),
    ("Vaccination error", "Vaccination error", 0, 23),
    ("Contraindication to vaccination", "Contraindication to vaccination", 1, 12),
    ("Inappropriate schedule", "Inappropriate schedule of product administration", 0, 7),
    ("Inappropriate patient age", "Product administered to patient of inappropriate age", 0, 7),
    ("Overdose", "Overdose", 0, 5),
    ("Product prescribing issue", "Product prescribing issue", 0, 5),
    ("Expired product administered", "Expired product administered", 0, 4),
    ("Incorrect dose administered", "Incorrect dose administered", 0, 4),
]
# Shown separately from the error bucket: not a quality-assurance failure;
# corroborates the reporting-population shift.
POPSHIFT = [
    ("Exposure during pregnancy", "Exposure during pregnancy", 1, 5),
]


def _verify_against_source():
    src = pd.read_csv(TABLES / "temporal_jev_pt_shift.csv")
    lookup = {r["reaction_pt"]: (int(r["pre_n"]), int(r["post_n"]))
              for _, r in src.iterrows()}
    for _, key, pre, post in CLASSICAL + ERRORS + POPSHIFT:
        assert key in lookup, f"MISSING {key} in temporal_jev_pt_shift.csv"
        assert lookup[key] == (pre, post), (
            f"MISMATCH {key}: figure has ({pre},{post}), CSV has {lookup[key]}"
        )
    qtr = pd.read_csv(TABLES / "temporal_jev_quarterly.csv")
    n_pre = int((qtr["quarter"].str[:4].astype(int) < 2022).sum())
    n_post = len(qtr) - n_pre
    assert (n_pre, n_post) == (N_PRE_Q, N_POST_Q), (
        f"Quarter counts ({n_pre},{n_post}) differ from ({N_PRE_Q},{N_POST_Q})"
    )
    print("Figure counts verified against temporal_jev_pt_shift.csv "
          "and temporal_jev_quarterly.csv")


def build():
    _verify_against_source()

    groups = [(CLASSICAL, BLUE, "classical"),
              (ERRORS, VERMIL, "error"),
              (POPSHIFT, ORANGE, "popshift")]
    rows = []
    for items, colour, cat in groups:
        for label, _key, pre, post in items:
            rows.append((label, pre / N_PRE_Q, post / N_POST_Q, colour))

    rows = rows[::-1]  # popshift, errors, classical from bottom to top
    labels = [r[0] for r in rows]
    pre_rate = [r[1] for r in rows]
    post_rate = [r[2] for r in rows]
    colours = [r[3] for r in rows]

    y = range(len(rows))
    h = 0.38

    fig, ax = plt.subplots(figsize=(7.6, 5.6))
    ax.barh([i + h / 2 for i in y], pre_rate, height=h, color=GREY, alpha=0.85,
            edgecolor="none", zorder=2)
    ax.barh([i - h / 2 for i in y], post_rate, height=h, color=colours, alpha=0.95,
            edgecolor="none", zorder=2)

    ax.set_yticks(list(y))
    ax.set_yticklabels(labels)
    ax.set_xlabel("Reports per quarter (136 pre-2022 quarters; 18 from 2022 onwards)")
    ax.set_title("Per-quarter Japanese encephalitis vaccine reporting rates, "
                 "pre-2022 vs 2022 onwards")

    # Group dividers.
    n_pop, n_err = len(POPSHIFT), len(ERRORS)
    div_pop_err = n_pop - 0.5
    div_err_cls = n_pop + n_err - 0.5
    for d in (div_pop_err, div_err_cls):
        ax.axhline(d, color="#cccccc", linewidth=0.8, linestyle="--", zorder=1)

    xmax = ax.get_xlim()[1]
    ax.text(xmax * 0.98, div_err_cls + len(CLASSICAL) / 2,
            "Classical reactions\n(rate roughly steady)", ha="right", va="center",
            color=BLUE, fontsize=8, fontweight="bold")
    ax.text(xmax * 0.98, div_pop_err + n_err / 2,
            "Administrative errors\n(emerge from ~0)", ha="right", va="center",
            color=VERMIL, fontsize=8, fontweight="bold")

    handles = [
        Patch(facecolor=GREY, alpha=0.85, label="Pre-2022 (per quarter)"),
        Patch(facecolor=BLUE, alpha=0.95, label="2022+ classical reaction"),
        Patch(facecolor=VERMIL, alpha=0.95, label="2022+ administrative error"),
        Patch(facecolor=ORANGE, alpha=0.95, label="2022+ population-shift indicator"),
    ]
    ax.legend(handles=handles, loc="lower right", frameon=False)

    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)

    fig.tight_layout()
    cwd = os.getcwd()
    os.chdir(FIGURES)
    try:
        for ext in ("pdf", "png"):
            fig.savefig(f"figure_jev_pt_shift.{ext}")
    finally:
        os.chdir(cwd)
    plt.close(fig)
    print(f"Wrote {FIGURES / 'figure_jev_pt_shift.pdf'} (+ .png)")


# Usage: python scripts/13_figure_jev_pt_shift.py

if __name__ == "__main__":
    build()
